apiVersion: v1
kind: Secret
metadata:
  name: signin-db-secret
  namespace: hummingbird-signin
type: Opaque
stringData:
  username: "postgres"
  password: "postgres"

---

apiVersion: v1
kind: Secret
metadata:
  name: signin-jwt-secret
  namespace: hummingbird-signin
type: Opaque
stringData:
  secret-key: "bcdfghijklmnopqurstblablathisis256yetidksoimcooked"