apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: hummingbird-api
type: Opaque
stringData:
  username: "user"
  password: "password"

---

apiVersion: v1
kind: Secret
metadata:
  name: api-adminkey
  namespace: hummingbird-api
type: Opaque
stringData:
  admin-key: "12345-abcde"
