apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: hummingbird-api
type: Opaque
stringData:
  username: "postgres"
  password: "postgres"

---

apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: hummingbird-api
type: Opaque
stringData:
  admin-key: "hb-admin-dev-key"

---

apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: hummingbird-api
type: Opaque
stringData:
  secret-key: "bcdfghijklmnopqurstblablathisis256yetidksoimcooked"
