apiVersion: apps/v1
kind: Deployment
metadata:
  name: hummingbird-admin
  namespace: hummingbird-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hummingbird-admin
  template:
    metadata:
      labels:
        app: hummingbird-admin
    spec:
      containers:
        - name: admin
          image: pemapol/hummingbird-admin:latest
          ports:
            - containerPort: 80
          env:
            - name: API_URL
              value: http://hummingbird-api.hummingbird-api.svc.cluster.local:5000
---
apiVersion: v1
kind: Service
metadata:
  name: hummingbird-admin
  namespace: hummingbird-admin
spec:
  selector:
    app: hummingbird-admin
  ports:
    - port: 80
      targetPort: 80
