apiVersion: v1
kind: LimitRange
metadata:
  name: argocd-defaults
  namespace: argocd
spec:
  limits:
    - type: Container
      default:
        cpu: 130m
        memory: 160Mi
      defaultRequest:
        cpu: 50m
        memory: 64Mi
      max:
        cpu: 500m
        memory: 512Mi
