resources:
  - ../../../hummingbird-api/api/namespace.yaml
  - ../../../hummingbird-api/api/secrets.yaml
  - ../../../hummingbird-api/api/rbac.yaml
  - ../../../hummingbird-api/api/postgres.yaml
  - ../../../hummingbird-api/api/api.yaml